-- MySQL Script generated by MySQL Workbench
-- Fri Dec 16 19:51:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` VARCHAR(50) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(32) NOT NULL,
  `fecha_creación` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`mail` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`datoseze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datoseze` (
  `id` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `posicion` VARCHAR(100) NULL,
  `edad` INT NOT NULL,
  `instagram` VARCHAR(100) NULL,
  `linkedin` VARCHAR(100) NULL,
  `github` VARCHAR(100) NULL,
  `fotoperfil` LONGTEXT NULL,
  `aboutme` VARCHAR(255) NULL,
  `rutacv` VARCHAR(100) NULL,
  `usuario_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datoseze_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_datoseze_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudios` (
  `id` INT NULL AUTO_INCREMENT,
  `institucion` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `periodo` VARCHAR(50) NULL,
  `descripcion` LONGTEXT NULL,
  `imagen` LONGTEXT NULL,
  `alt` VARCHAR(45) NULL,
  `datoseze_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudios_datoseze1_idx` (`datoseze_id` ASC),
  CONSTRAINT `fk_estudios_datoseze1`
    FOREIGN KEY (`datoseze_id`)
    REFERENCES `mydb`.`datoseze` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`experiencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`experiencias` (
  `id` INT NULL AUTO_INCREMENT,
  `logo` LONGTEXT NULL,
  `altimg` VARCHAR(50) NULL,
  `puesto` VARCHAR(150) NULL,
  `empesa` VARCHAR(45) NULL,
  `inicio` VARCHAR(45) NULL,
  `fin` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(100) NULL,
  `descripcion` LONGTEXT NULL,
  `datoseze_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_experiencias_datoseze1_idx` (`datoseze_id` ASC),
  CONSTRAINT `fk_experiencias_datoseze1`
    FOREIGN KEY (`datoseze_id`)
    REFERENCES `mydb`.`datoseze` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` LONGTEXT NULL,
  `imagen` LONGTEXT NULL,
  `alto` VARCHAR(40) NULL,
  `porcentaje` INT NULL,
  `estiloporc` VARCHAR(45) NULL,
  `datoseze_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skills_datoseze1_idx` (`datoseze_id` ASC),
  CONSTRAINT `fk_skills_datoseze1`
    FOREIGN KEY (`datoseze_id`)
    REFERENCES `mydb`.`datoseze` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesor` (
  `id` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `posicion` VARCHAR(100) NULL,
  `usuario_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_profesor_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_profesor_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
